### ISSUE TITLE
Allows `read_vplots` read `GRanges` with directions

### ISSUE THREAD

**Issue by gongx030** [gongx030/seatac#2]

**Comment by gongx030** [comment]
@dsouz072 In update `v0.3.3009`, an argument `ignore_strand` was added to `read_vplots`.  When `ignore_strand=FALSE`, `read_vplots` will automatically flip the V-plots on the minus strand.  See example notebook here: https://colab.research.google.com/github/gongx030/seatac_project/blob/master/notebooks/Check_ignore_strand_options_in_read_vplots.ipynb

**Comment by gongx030** [comment]
@dsouz072 By default, `ignore_strand` is `TRUE`, so the default behavior of `read_vplots` won't change.

**Comment by dsouz072** [comment]
Thank you @gongx030. I will take a look at the notebook.
