### ISSUE TITLE
Colab: rlang version issue

### ISSUE THREAD

**Issue by dsouz072** [gongx030/seatac#3]
@gongx030 This [gist](https://colab.research.google.com/gist/dsouz072/60fa6dcc5efe233961f28e7a7f4e97ce/untitled4.ipynb) shows even if we update rlang to the newest version and it is loaded in the NameSPACE it still throws an error installing seATAC. 

The tfdatasets package throws this error.

**Comment by gongx030** [comment]
@dsouz072 Fixed in `v0.3.3011`

https://colab.research.google.com/gist/gongx030/e25f9a3ecb37716a7ef62ec2c3858b61/copy-of-untitled4.ipynb

**Comment by dsouz072** [comment]
Thank you, I'll give it a try.

**Comment by dsouz072** [comment]
I ran the script and could successfully install the package.
